### ISSUE TITLE
TypeError - getmempoolentry for 'fee' (null)

### ISSUE THREAD

**Issue by joej** [KanoczTomas/01Cnode#45] opened 2018-05-01 19:35 UTC
joe@n1-standard-ubu1604:~/src/01Cnode$ node server.js
logging to file: /mnt/disks/sdb/joe_src/01Cnode/server.log
server is now running on port 3000

There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null
There was an error during getmempoolentry RPC
error is: TypeError: Cannot read property 'fee' of null

**Comment by KanoczTomas** [comment] 2018-05-21 07:52
Hi, sorry for the late reply. This is a gracefull error when we can not get back the tx through RPC and no fee is assigned to it. If you run your node on an SSD you will see only few of these errors, on spinning disks way more. It happens when more transactions come in than your bitcoind can handle.

Closing as it is not a bug, feel free to reopen incase you need to.

I am working on a refactor from scratch, so stay tuned. The new backend should be much quicker, robust and modular.

**Closed as completed by KanoczTomas** 2018-05-21 07:52 UTC
